language: bash
arch:
        packages:
                - bash
                - git
                - archiso
        script:
                - bash test.sh

script:
        - "travis_wait 30 sleep 1800 &"
        - curl -s https://raw.githubusercontent.com/fossasia/arch-travis/master/arch-travis.sh | bash
