version: ~> 1.0
language: bash
script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
services:
  - docker
archlinux:
  packages:
    - bash
    - git
  mount:
    - ~/.pkg-cache:/var/cache/pacman/pkg
  before_install:
    - "sudo ln -s /dev/null /etc/pacman.d/hooks/package-cleanup.hook"
  script:
    - "bash test.sh"

